-- Initial ZeroSeal API schema. Generated from prisma/schema.prisma and kept
-- explicit so local migration validation does not depend on a live database.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE "ClaimStatus" AS ENUM ('DRAFT', 'AWAITING_PROOF', 'PROOF_RECEIVED', 'VERIFYING', 'VERIFIED', 'AWAITING_WALLET_SIGNATURE', 'SUBMITTED', 'CONFIRMED', 'RECEIPT_ISSUED', 'PROOF_REJECTED', 'TRANSACTION_FAILED', 'EXPIRED', 'CANCELLED');
CREATE TYPE "VerificationJobStatus" AS ENUM ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEAD_LETTERED');
CREATE TYPE "VerificationBoundary" AS ENUM ('STRUCTURAL', 'CRYPTOGRAPHIC', 'SOROBAN', 'REGISTRY', 'TRANSACTION');
CREATE TYPE "VerificationResultStatus" AS ENUM ('PENDING', 'PASSED', 'FAILED', 'UNAVAILABLE');
CREATE TYPE "ChainTransactionStatus" AS ENUM ('SUBMITTED', 'PENDING', 'CONFIRMED', 'FAILED', 'UNKNOWN');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'CONFIRMED', 'FAILED');

CREATE TABLE "WalletAccount" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "address" TEXT NOT NULL, "network" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "WalletAccount_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Organisation" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Organisation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Programme" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "identifier" TEXT NOT NULL, "name" TEXT NOT NULL, "organisationId" UUID NOT NULL, "network" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Programme_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProgrammeSnapshot" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "identifier" TEXT NOT NULL, "programmeId" UUID NOT NULL, "description" TEXT, "startsAt" TIMESTAMP(3) NOT NULL, "expiresAt" TIMESTAMP(3), "immutableAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ProgrammeSnapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ImpactPolicy" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "identifier" TEXT NOT NULL, "programmeId" UUID NOT NULL, "rule" TEXT NOT NULL, "publicThreshold" TEXT NOT NULL, "circuitId" TEXT NOT NULL, "expectedPublicInputs" JSONB NOT NULL, "registryContract" TEXT NOT NULL, "verifierContract" TEXT NOT NULL, "network" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ImpactPolicy_pkey" PRIMARY KEY ("id"));
CREATE TABLE "EvidenceCommitment" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "network" TEXT NOT NULL, "commitment" TEXT NOT NULL, "manifestDigest" TEXT NOT NULL, "fileCount" INTEGER NOT NULL, "metadata" JSONB NOT NULL, "circuitBound" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "EvidenceCommitment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Claim" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "status" "ClaimStatus" NOT NULL DEFAULT 'DRAFT', "idempotencyKey" TEXT NOT NULL, "network" TEXT NOT NULL, "programmeId" UUID NOT NULL, "programmeSnapshotId" UUID NOT NULL, "impactPolicyId" UUID NOT NULL, "walletAccountId" UUID NOT NULL, "circuitId" TEXT NOT NULL, "researcherCommitment" TEXT NOT NULL, "nullifier" TEXT, "evidenceCommitmentId" UUID, "currentLifecycleError" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Claim_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ClaimPublicInput" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "claimId" UUID NOT NULL, "position" INTEGER NOT NULL, "name" TEXT NOT NULL, "valueHex" TEXT NOT NULL, "digest" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ClaimPublicInput_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProofArtifact" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "claimId" UUID NOT NULL, "schemaVersion" TEXT NOT NULL, "proofEncoding" TEXT NOT NULL, "proofByteLength" INTEGER NOT NULL, "publicInputByteLength" INTEGER NOT NULL, "artifactDigest" TEXT NOT NULL, "proofDigest" TEXT NOT NULL, "publicInputDigest" TEXT NOT NULL, "sanitizedMetadata" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ProofArtifact_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VerificationJob" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "claimId" UUID NOT NULL, "proofArtifactId" UUID, "status" "VerificationJobStatus" NOT NULL DEFAULT 'QUEUED', "attemptCount" INTEGER NOT NULL DEFAULT 0, "verifierVersion" TEXT, "proofArtifactDigest" TEXT, "publicInputDigest" TEXT, "durationMs" INTEGER, "errorCode" TEXT, "sanitizedError" TEXT, "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "VerificationJob_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VerificationResult" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "claimId" UUID NOT NULL, "boundary" "VerificationBoundary" NOT NULL, "status" "VerificationResultStatus" NOT NULL, "verifierVersion" TEXT, "inputDigest" TEXT, "outputDigest" TEXT, "errorCode" TEXT, "sanitizedMessage" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "VerificationResult_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ChainTransaction" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "network" TEXT NOT NULL, "transactionHash" TEXT NOT NULL, "walletAccountId" UUID, "claimId" UUID, "ledgerNumber" INTEGER, "sourceAccount" TEXT, "contractId" TEXT, "method" TEXT NOT NULL, "operationType" TEXT NOT NULL, "status" "ChainTransactionStatus" NOT NULL DEFAULT 'SUBMITTED', "feeCharged" TEXT, "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "confirmedAt" TIMESTAMP(3), "failedAt" TIMESTAMP(3), "rawResponseDigest" TEXT, "idempotencyKey" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ChainTransaction_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ClaimReceipt" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "receiptId" TEXT NOT NULL, "claimId" UUID NOT NULL, "programmeIdentifier" TEXT NOT NULL, "snapshotIdentifier" TEXT NOT NULL, "policyIdentifier" TEXT NOT NULL, "circuitId" TEXT NOT NULL, "walletAddress" TEXT NOT NULL, "researcherCommitment" TEXT NOT NULL, "evidenceCommitmentId" UUID, "nullifier" TEXT, "publicInputDigest" TEXT NOT NULL, "proofArtifactDigest" TEXT NOT NULL, "verificationResult" JSONB NOT NULL, "transactionId" UUID NOT NULL, "transactionHash" TEXT NOT NULL, "ledgerNumber" INTEGER NOT NULL, "registryContract" TEXT NOT NULL, "verifierContract" TEXT NOT NULL, "network" TEXT NOT NULL, "explorerTransactionUrl" TEXT NOT NULL, "explorerAccountUrl" TEXT NOT NULL, "explorerRegistryUrl" TEXT NOT NULL, "explorerVerifierUrl" TEXT NOT NULL, "receiptDigest" TEXT NOT NULL, "issuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ClaimReceipt_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Payment" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "walletAccountId" UUID NOT NULL, "claimId" UUID, "network" TEXT NOT NULL, "transactionHash" TEXT, "amount" TEXT NOT NULL, "assetCode" TEXT NOT NULL, "destination" TEXT NOT NULL, "status" "PaymentStatus" NOT NULL DEFAULT 'PENDING', "confirmedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Payment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VerificationCredit" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "paymentId" UUID NOT NULL, "organisationId" UUID, "quantity" INTEGER NOT NULL, "remaining" INTEGER NOT NULL, "expiresAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "VerificationCredit_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "WalletAccount_address_key" ON "WalletAccount"("address");
CREATE INDEX "WalletAccount_address_idx" ON "WalletAccount"("address");
CREATE INDEX "WalletAccount_network_address_idx" ON "WalletAccount"("network", "address");
CREATE UNIQUE INDEX "Organisation_slug_key" ON "Organisation"("slug");
CREATE UNIQUE INDEX "Programme_identifier_key" ON "Programme"("identifier");
CREATE INDEX "Programme_identifier_idx" ON "Programme"("identifier");
CREATE UNIQUE INDEX "ProgrammeSnapshot_programmeId_identifier_key" ON "ProgrammeSnapshot"("programmeId", "identifier");
CREATE INDEX "ProgrammeSnapshot_programmeId_idx" ON "ProgrammeSnapshot"("programmeId");
CREATE UNIQUE INDEX "ImpactPolicy_programmeId_identifier_key" ON "ImpactPolicy"("programmeId", "identifier");
CREATE INDEX "ImpactPolicy_programmeId_idx" ON "ImpactPolicy"("programmeId");
CREATE INDEX "ImpactPolicy_circuitId_idx" ON "ImpactPolicy"("circuitId");
CREATE UNIQUE INDEX "EvidenceCommitment_network_commitment_key" ON "EvidenceCommitment"("network", "commitment");
CREATE INDEX "EvidenceCommitment_commitment_idx" ON "EvidenceCommitment"("commitment");
CREATE UNIQUE INDEX "Claim_walletAccountId_idempotencyKey_key" ON "Claim"("walletAccountId", "idempotencyKey");
CREATE UNIQUE INDEX "Claim_network_circuitId_nullifier_key" ON "Claim"("network", "circuitId", "nullifier");
CREATE INDEX "Claim_walletAccountId_idx" ON "Claim"("walletAccountId");
CREATE INDEX "Claim_programmeId_idx" ON "Claim"("programmeId");
CREATE INDEX "Claim_status_idx" ON "Claim"("status");
CREATE INDEX "Claim_nullifier_idx" ON "Claim"("nullifier");
CREATE UNIQUE INDEX "ClaimPublicInput_claimId_position_key" ON "ClaimPublicInput"("claimId", "position");
CREATE INDEX "ClaimPublicInput_claimId_idx" ON "ClaimPublicInput"("claimId");
CREATE UNIQUE INDEX "ProofArtifact_claimId_artifactDigest_key" ON "ProofArtifact"("claimId", "artifactDigest");
CREATE INDEX "ProofArtifact_artifactDigest_idx" ON "ProofArtifact"("artifactDigest");
CREATE INDEX "VerificationJob_claimId_idx" ON "VerificationJob"("claimId");
CREATE INDEX "VerificationJob_status_idx" ON "VerificationJob"("status");
CREATE UNIQUE INDEX "VerificationResult_claimId_boundary_key" ON "VerificationResult"("claimId", "boundary");
CREATE INDEX "VerificationResult_claimId_idx" ON "VerificationResult"("claimId");
CREATE INDEX "VerificationResult_boundary_status_idx" ON "VerificationResult"("boundary", "status");
CREATE UNIQUE INDEX "ChainTransaction_network_transactionHash_key" ON "ChainTransaction"("network", "transactionHash");
CREATE UNIQUE INDEX "ChainTransaction_claimId_idempotencyKey_key" ON "ChainTransaction"("claimId", "idempotencyKey");
CREATE INDEX "ChainTransaction_walletAccountId_idx" ON "ChainTransaction"("walletAccountId");
CREATE INDEX "ChainTransaction_claimId_idx" ON "ChainTransaction"("claimId");
CREATE INDEX "ChainTransaction_status_idx" ON "ChainTransaction"("status");
CREATE INDEX "ChainTransaction_transactionHash_idx" ON "ChainTransaction"("transactionHash");
CREATE UNIQUE INDEX "ClaimReceipt_receiptId_key" ON "ClaimReceipt"("receiptId");
CREATE UNIQUE INDEX "ClaimReceipt_claimId_key" ON "ClaimReceipt"("claimId");
CREATE UNIQUE INDEX "ClaimReceipt_transactionId_key" ON "ClaimReceipt"("transactionId");
CREATE INDEX "ClaimReceipt_receiptId_idx" ON "ClaimReceipt"("receiptId");
CREATE INDEX "ClaimReceipt_transactionHash_idx" ON "ClaimReceipt"("transactionHash");
CREATE INDEX "Payment_walletAccountId_idx" ON "Payment"("walletAccountId");
CREATE INDEX "Payment_transactionHash_idx" ON "Payment"("transactionHash");
CREATE INDEX "Payment_status_idx" ON "Payment"("status");
CREATE INDEX "VerificationCredit_paymentId_idx" ON "VerificationCredit"("paymentId");

ALTER TABLE "Programme" ADD CONSTRAINT "Programme_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProgrammeSnapshot" ADD CONSTRAINT "ProgrammeSnapshot_programmeId_fkey" FOREIGN KEY ("programmeId") REFERENCES "Programme"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ImpactPolicy" ADD CONSTRAINT "ImpactPolicy_programmeId_fkey" FOREIGN KEY ("programmeId") REFERENCES "Programme"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_programmeId_fkey" FOREIGN KEY ("programmeId") REFERENCES "Programme"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_programmeSnapshotId_fkey" FOREIGN KEY ("programmeSnapshotId") REFERENCES "ProgrammeSnapshot"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_impactPolicyId_fkey" FOREIGN KEY ("impactPolicyId") REFERENCES "ImpactPolicy"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_walletAccountId_fkey" FOREIGN KEY ("walletAccountId") REFERENCES "WalletAccount"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_evidenceCommitmentId_fkey" FOREIGN KEY ("evidenceCommitmentId") REFERENCES "EvidenceCommitment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ClaimPublicInput" ADD CONSTRAINT "ClaimPublicInput_claimId_fkey" FOREIGN KEY ("claimId") REFERENCES "Claim"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProofArtifact" ADD CONSTRAINT "ProofArtifact_claimId_fkey" FOREIGN KEY ("claimId") REFERENCES "Claim"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "VerificationJob" ADD CONSTRAINT "VerificationJob_claimId_fkey" FOREIGN KEY ("claimId") REFERENCES "Claim"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "VerificationJob" ADD CONSTRAINT "VerificationJob_proofArtifactId_fkey" FOREIGN KEY ("proofArtifactId") REFERENCES "ProofArtifact"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "VerificationResult" ADD CONSTRAINT "VerificationResult_claimId_fkey" FOREIGN KEY ("claimId") REFERENCES "Claim"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ChainTransaction" ADD CONSTRAINT "ChainTransaction_walletAccountId_fkey" FOREIGN KEY ("walletAccountId") REFERENCES "WalletAccount"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ChainTransaction" ADD CONSTRAINT "ChainTransaction_claimId_fkey" FOREIGN KEY ("claimId") REFERENCES "Claim"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ClaimReceipt" ADD CONSTRAINT "ClaimReceipt_claimId_fkey" FOREIGN KEY ("claimId") REFERENCES "Claim"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ClaimReceipt" ADD CONSTRAINT "ClaimReceipt_evidenceCommitmentId_fkey" FOREIGN KEY ("evidenceCommitmentId") REFERENCES "EvidenceCommitment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ClaimReceipt" ADD CONSTRAINT "ClaimReceipt_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "ChainTransaction"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_walletAccountId_fkey" FOREIGN KEY ("walletAccountId") REFERENCES "WalletAccount"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_claimId_fkey" FOREIGN KEY ("claimId") REFERENCES "Claim"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "VerificationCredit" ADD CONSTRAINT "VerificationCredit_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
